version: '3.4'
services:
  db:
    container_name: postgres
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - development.env
    ports:
      - 5432:5432
    networks:
      - SIGS_development
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
      
  sigs:
    container_name: sigs
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - development.env
    volumes:
      - .:/sigs
    ports:
      - "3000:3000"
    links:  
      - db
    depends_on:
      - db
    networks:
      - SIGS_development

volumes:
  dev-postgres-data: {}

networks:
  SIGS_development:
    driver: bridge
